backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "title" # Used in routes, e.g., /admin/collections/blog
    label: "Titulo" # Used in the UI
    folder: "src/info/title" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "title"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Icono", name: "icon", widget: "image"}
      - {label: "Url", name: "urltitle", widget: "string"}
  - name: "subtitle" # Used in routes, e.g., /admin/collections/blog
    label: "SubTitulo" # Used in the UI
    folder: "src/info/subtitle" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{subtitle}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "subtitle"}
      - {label: "Titulo Padre", name: "title", widget: "string"}
      - {label: "Icono", name: "icon", widget: "image"}
      - {label: "Url titulo", name: "urltitle", widget: "string"}
      - {label: "SubTitulo", name: "subtitle", widget: "string"}
      - {label: "Url propia", name: "urlsubtitle", widget: "string"}
      - {label: "Pais", name: "country", widget: "string"}
  - name: "subsubtitle" # Used in routes, e.g., /admin/collections/blog
    label: "Otro SubTitulo" # Used in the UI
    folder: "src/info/subsubtitle" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{subtitle}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "subtitle"}
      - {label: "Titulo Subtitulo", name: "subtitle", widget: "string"}
      - {label: "Url Subtitulo", name: "urlsubtitle", widget: "string"}
      - {label: "Sub-SubTitulo", name: "subsubtitle", widget: "string"}
      - {label: "Url propia", name: "urlsubsubtitle", widget: "string"}
      - {label: "Pais", name: "country", widget: "string"}
  - name: "info" # Used in routes, e.g., /admin/collections/blog
    label: "Informacion" # Used in the UI
    folder: "src/info/information" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{subtitle}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "subtitle"}
      - {label: "SubTitulo", name: "subtitle", widget: "string"}
      - {label: "Url subtitulo", name: "urlsubtitle", widget: "string"}
      - {label: "Url sub-subtitulo", name: "urlsubsubtitle", widget: "string", required: false}
      - {label: "Pais", name: "country", widget: "string"}
      - {label: "Imagen 1", name: "imageOne", widget: "image", required: false}
      - {label: "Imagen 2", name: "imageTwo", widget: "image", required: false}
      - {label: "Imagen 3", name: "imageThree", widget: "image", required: false}
      - {label: "Imagen 4", name: "imageFour", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

