backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "title" # Used in routes, e.g., /admin/collections/blog
    label: "Titulo" # Used in the UI
    folder: "src/info/title" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "title"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Icono", name: "icon", widget: "image"}
      - {label: "Url", name: "urltitle", widget: "string"}
      - {label: "Relevancia (del 0 al 9)", name: "score", widget: "number", min: 0, max: 9}
  - name: "subtitle" # Used in routes, e.g., /admin/collections/blog
    label: "SubTitulo" # Used in the UI
    folder: "src/info/subtitle" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{subtitle}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "subtitle"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Url Titulo", name: "urltitle", widget: "string"}
      - {label: "Titulo Padre", name: "titleFather", widget: "string"}
      - {label: "Icono", name: "icon", widget: "image"}
      - {label: "Url Padre", name: "urltitleFather", widget: "string"}
      - {label: "Pais", name: "country", widget: "string"}
      - {label: "Relevancia (del 0 al 9)", name: "score", widget: "number", min: 0, max: 9}
  - name: "info" # Used in routes, e.g., /admin/collections/blog
    label: "Informacion" # Used in the UI
    folder: "src/info/information" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{subtitle}} {{country}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "string", default: "{{subtitle}} - {{country}}"}
      - {label: "SubTitulo", name: "subtitle", widget: "string"}
      - {label: "Url subtitulo", name: "urlsubtitle", widget: "string"}
      - {label: "Pais", name: "country", widget: "string"}
      - {label: "Video", name: "video", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "forms" # Used in routes, e.g., /admin/collections/blog
    label: "Formularios" # Used in the UI
    folder: "src/info/form" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
        - {label: "Layout", name: "layout", widget: "hidden", default: "subtitle"}
        - {label: "Titulo del formulario", name: "title", widget: "string"}
        - {label: "ID de formulario", name: "id", widget: "string"}
        - {label: "Obligatorio el archivo adjunto", name: "attachFile", widget: "boolean", default: true}
  - name: "formFields" # Used in routes, e.g., /admin/collections/blog
    label: "Campos de los Formularios" # Used in the UI
    folder: "src/info/formFields" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "subtitle"}
      - {label: "Titulo del campo", name: "title", widget: "string"}
      - {label: "ID de el/los campo/s", name: "id", widget: "string"}
      - {label: "Nombre del campo", name: "name", widget: "string"}
      - {label: "Texto de ayuda", name: "helperText", widget: "string", required: false}
      - {label: "Campo requerido", name: "required", widget: "boolean", default: false}
      - {label: "Fecha", name: "dateCheckbox", widget: "boolean", default: false}
      - {label: "Hora", name: "hourCheckbox", widget: "boolean", default: false}
  - name: "tagZendesk" # Used in routes, e.g., /admin/collections/blog
    label: "Tags de Zendesk" # Used in the UI
    folder: "src/info/tagZendesk" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "subtitle"}
      - {label: "Titulo del Formulario", name: "title", widget: "string"}
      - {label: "Tag Uno", name: "tagOne", widget: "string"}
      - {label: "Tag Dos (Pais)", name: "tagTwo", widget: "string", required: false}
      - {label: "Tag Tres (Socio/Buyer)", name: "tagThree", widget: "string", required: false}
