backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    extension: "json"
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Icono", name: "thumbnail", widget: "image", required: false}
      - {label: "SubTitulos", name: "subtitles", widget: "object", fields:
        - {label: "SubTitulo", name: "subtitle", widget: "string"}
          - {label: "Informacion", name: "info", widget: "object", fields:
            - {label: "Info Titulo", name: "infoTitle", widget: "string"}
            - {label: "Contenido", name: "content", widget: "string"}
      }